In [1]:
# ! pip install scrublet

https://satijalab.org/seurat/archive/v2.4/conversion_vignette.html 
перевод адата в сеурат объект

https://doi.org/10.1016/j.isci.2021.102151
Wyler et al. (2021) iScience

Ссылка:  https://cellxgene.cziscience.com/collections/d0e9c47b-4ce7-4f84-b182-eddcfa0b2658


#### extraction of viral genes: https://github.com/BIMSBbioinfo/Ewyler_SARS-CoV/blob/master/Processing/Process_Seurat.rmd


#### methods: https://www.cell.com/cms/10.1016/j.isci.2021.102151/attachment/12909dee-01ca-466f-86f9-3e997d6461dd/mmc1

#  starting with prepocessed counts

In [1]:
import scanpy as sc
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import scanpy.external as sce
import sys
import scipy

In [3]:
counts = pd.read_csv('/Users/sofialuk/Desktop/thesis/h1299/h1299_counts/preprocessed_h1299.csv', sep=',')

In [6]:
counts

,Unnamed: 0,ENSG00000146038,ENSG00000136536,ENSG00000203809,ENSG00000116679,ENSG00000160360,ENSG00000165282,ENSG00000023330,ENSG00000105371,ENSG00000117242,...,ENSG00000137760,ENSG00000004534,ENSG00000025423,ENSG00000164543,ENSG00000073578,ENSG00000163596,ENSG00000224152,ENSG00000145388,ENSG00000196776,ENSG00000181513
0,H1299-mock-36h-A_AAAAACAATTTT,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,H1299-mock-36h-A_AAAACCACAAAT,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,H1299-mock-36h-A_AAAACCTTATCC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,H1299-mock-36h-A_AAAACGCAATAA,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,H1299-mock-36h-A_AAAACGCCCATC,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46500,H1299-S2-36h-B_TTTTGTGCTACC,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46501,H1299-S2-36h-B_TTTTTGAGTCCA,0.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
46502,H1299-S2-36h-B_TTTTTGCAGGTT,0.0,1.0,0.0,3.0,0.0,2.0,0.0,0.0,0.0,...,2.0,8.0,0.0,4.0,5.0,0.0,0.0,0.0,1.0,0.0
46503,H1299-S2-36h-B_TTTTTGCCGCTT,0.0,4.0,0.0,1.0,0.0,2.0,2.0,0.0,0.0,...,0.0,5.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0
46504,H1299-S2-36h-B_TTTTTTCAACTT,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,3.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [5]:
genes = list(counts.columns[1:])

In [6]:
counts4 = counts[counts['Unnamed: 0'].str.contains('-4')]
counts4.index = counts4['Unnamed: 0']
counts4.drop('Unnamed: 0', axis = 1)
counts4 = counts4.groupby([s.split('_')[0] for s in counts4.index.values]).sum().T
counts4.to_csv('h1299_4h_sum.csv')
counts4

/var/folders/7h/_mrm1yh5299bvqql6k199xb00000gn/T/ipykernel_50460/3439663631.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  counts4 = counts4.groupby([s.split('_')[0] for s in counts4.index.values]).sum().T

                 H1299-mock-4h-A  H1299-mock-4h-B
ENSG00000146038              9.0              6.0
ENSG00000136536           2831.0           2157.0
ENSG00000203809             12.0              4.0
ENSG00000116679            947.0            724.0
ENSG00000160360            285.0            232.0
...                          ...              ...
ENSG00000163596            274.0            219.0
ENSG00000224152             38.0             27.0
ENSG00000145388            208.0            167.0
ENSG00000196776           1708.0           1378.0
ENSG00000181513             41.0             33.0

[15645 rows x 2 columns]

In [7]:
counts12 = counts[counts['Unnamed: 0'].str.contains('-12')]
counts12.index = counts12['Unnamed: 0']
counts12.drop('Unnamed: 0', axis = 1)
counts12 = counts12.groupby([s.split('_')[0] for s in counts12.index.values]).sum().T

counts12[['H1299-mock-4h-A', 'H1299-mock-4h-B']] = counts4[['H1299-mock-4h-A', 'H1299-mock-4h-B']]

counts12.to_csv('h1299_12h_sum.csv')
counts12

/var/folders/7h/_mrm1yh5299bvqql6k199xb00000gn/T/ipykernel_50460/868083225.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  counts12 = counts12.groupby([s.split('_')[0] for s in counts12.index.values]).sum().T

,H1299-S2-12h-A,H1299-S2-12h-B,H1299-mock-4h-A,H1299-mock-4h-B
ENSG00000146038,5.0,7.0,9.0,6.0
ENSG00000136536,1877.0,1876.0,2831.0,2157.0
ENSG00000203809,7.0,7.0,12.0,4.0
ENSG00000116679,777.0,707.0,947.0,724.0
ENSG00000160360,245.0,197.0,285.0,232.0
...,...,...,...,...
ENSG00000163596,225.0,176.0,274.0,219.0
ENSG00000224152,25.0,22.0,38.0,27.0
ENSG00000145388,119.0,136.0,208.0,167.0
ENSG00000196776,1085.0,1088.0,1708.0,1378.0
ENSG00000181513,38.0,30.0,41.0,33.0

In [8]:
counts24 = counts[counts['Unnamed: 0'].str.contains('24')]
counts24.index = counts24['Unnamed: 0']
counts24.drop('Unnamed: 0', axis = 1)
counts24 = counts24.groupby([s.split('_')[0] for s in counts24.index.values]).sum().T
counts24[['H1299-mock-4h-A', 'H1299-mock-4h-B']] = counts4[['H1299-mock-4h-A', 'H1299-mock-4h-B']]
counts24.to_csv('h1299_24h_sum.csv')
counts24

/var/folders/7h/_mrm1yh5299bvqql6k199xb00000gn/T/ipykernel_50460/93406689.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  counts24 = counts24.groupby([s.split('_')[0] for s in counts24.index.values]).sum().T

,H1299-S2-24h-A,H1299-S2-24h-B,H1299-mock-4h-A,H1299-mock-4h-B
ENSG00000146038,5.0,16.0,9.0,6.0
ENSG00000136536,1507.0,2066.0,2831.0,2157.0
ENSG00000203809,8.0,6.0,12.0,4.0
ENSG00000116679,664.0,789.0,947.0,724.0
ENSG00000160360,232.0,246.0,285.0,232.0
...,...,...,...,...
ENSG00000163596,160.0,238.0,274.0,219.0
ENSG00000224152,25.0,24.0,38.0,27.0
ENSG00000145388,118.0,175.0,208.0,167.0
ENSG00000196776,904.0,1147.0,1708.0,1378.0
ENSG00000181513,54.0,34.0,41.0,33.0

In [9]:
counts36 = counts[counts['Unnamed: 0'].str.contains('36')]
counts36.index = counts36['Unnamed: 0']
counts36.drop('Unnamed: 0', axis = 1)
counts36 = counts36.groupby([s.split('_')[0] for s in counts36.index.values]).sum().T
counts36.to_csv('h1299_36h_sum.csv')
counts36

/var/folders/7h/_mrm1yh5299bvqql6k199xb00000gn/T/ipykernel_50460/2127434153.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  counts36 = counts36.groupby([s.split('_')[0] for s in counts36.index.values]).sum().T

,H1299-S2-36h-A,H1299-S2-36h-B,H1299-mock-36h-A,H1299-mock-36h-B
ENSG00000146038,10.0,20.0,10.0,8.0
ENSG00000136536,2168.0,1958.0,1923.0,1304.0
ENSG00000203809,8.0,10.0,14.0,1.0
ENSG00000116679,820.0,692.0,761.0,549.0
ENSG00000160360,300.0,242.0,261.0,200.0
...,...,...,...,...
ENSG00000163596,259.0,199.0,210.0,155.0
ENSG00000224152,47.0,28.0,34.0,25.0
ENSG00000145388,190.0,161.0,163.0,111.0
ENSG00000196776,1009.0,967.0,1057.0,716.0
ENSG00000181513,38.0,40.0,52.0,31.0

In [10]:
counts36_1 = pd.DataFrame()
counts36_1[['H1299-mock-4h-A', 'H1299-mock-4h-B']] = counts4[['H1299-mock-4h-A', 'H1299-mock-4h-B']]
counts36_1[['H1299-S2-36h-A', 'H1299-S2-36h-B']] = counts36[['H1299-S2-36h-A', 'H1299-S2-36h-B']]
counts36_1

,H1299-mock-4h-A,H1299-mock-4h-B,H1299-S2-36h-A,H1299-S2-36h-B
ENSG00000146038,9.0,6.0,10.0,20.0
ENSG00000136536,2831.0,2157.0,2168.0,1958.0
ENSG00000203809,12.0,4.0,8.0,10.0
ENSG00000116679,947.0,724.0,820.0,692.0
ENSG00000160360,285.0,232.0,300.0,242.0
...,...,...,...,...
ENSG00000163596,274.0,219.0,259.0,199.0
ENSG00000224152,38.0,27.0,47.0,28.0
ENSG00000145388,208.0,167.0,190.0,161.0
ENSG00000196776,1708.0,1378.0,1009.0,967.0
ENSG00000181513,41.0,33.0,38.0,40.0

# DIFFERENTIAL EXPRESSION CASE VS CONTROL

In [11]:
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter

pandas2ri.activate()
DESeq2 = importr("DESeq2")

from rpy2.robjects import default_converter
from rpy2.robjects.conversion import rpy2py
base = importr("base")

During startup - Warning messages:
1: Setting LC_COLLATE failed, using "C"
2: Setting LC_TIME failed, using "C"
3: Setting LC_MESSAGES failed, using "C"
4: Setting LC_MONETARY failed, using "C"

In [12]:
def deseq(meta: pd.DataFrame, counts: pd.DataFrame, formula: str, ref: str, exp: str):
    # Calculate normalization factors
    dds = DESeq2.DESeqDataSetFromMatrix(
        countData=counts, colData=meta, design=ro.Formula(formula))
    
    dds = DESeq2.DESeq(dds) #parallel=True
    #estimateSizeFactors(dds, type = 'iterate')
    
    print(f"experiment_{exp}_vs_{ref}")
    resR = DESeq2.results(dds, name=f"experiment_{ref}_vs_{exp}")
    res = r_to_df(resR)
    res = res.sort_values("padj")
    res = res.loc[res["padj"] < 0.05]
    res = res.loc[res["log2FoldChange"].abs() > 0.5]

    return res


def r_to_df(r_df):
    with localconverter(default_converter + pandas2ri.converter):
        return rpy2py(base.as_data_frame(r_df))

In [13]:
counts = counts12

design = pd.DataFrame({
    "experiment": [sample_name.split("-")[1] for sample_name in counts.columns],
    #"hpi": [sample_name.split("-")[2] for sample_name in counts.columns],
}, index=counts.columns)

design

res = deseq(meta=design, counts=counts, formula="~experiment", ref="mock", exp="S2")

res.to_csv('h1299_DEGs_12h.csv')
res

R[write to console]: converting counts to integer mode

R[write to console]: estimating size factors

R[write to console]: estimating dispersions

R[write to console]: gene-wise dispersion estimates

R[write to console]: mean-dispersion relationship

R[write to console]: final dispersion estimates

R[write to console]: fitting model and testing

experiment_S2_vs_mock

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
ENSG00000023445,11233.635725,1.375779,0.114217,12.045324,2.052695e-33,2.464055e-29
ENSG00000277072,581.244169,-1.309840,0.165160,-7.930744,2.178366e-15,1.307455e-11
ENSG00000080824,245552.304553,-0.899579,0.117248,-7.672443,1.687515e-14,5.252972e-11
ENSG00000119004,1892.445235,-1.112573,0.145098,-7.667749,1.750407e-14,5.252972e-11
ENSG00000173421,864.227579,-1.101231,0.144256,-7.633885,2.277835e-14,5.468627e-11
...,...,...,...,...,...,...
ENSG00000109576,58.887638,0.977419,0.376721,2.594541,9.471742e-03,4.926291e-02
ENSG00000114279,180.205191,0.634203,0.244870,2.589956,9.598829e-03,4.972997e-02
ENSG00000180229,81.370133,-0.828918,0.320177,-2.588931,9.627429e-03,4.981975e-02
ENSG00000130052,140.579709,-0.670481,0.259039,-2.588345,9.643836e-03,4.987704e-02
ENSG00000220161,112.433345,-0.796123,0.307645,-2.587797,9.659179e-03,4.993488e-02

In [14]:
counts = counts24

design = pd.DataFrame({
    "experiment": [sample_name.split("-")[1] for sample_name in counts.columns],
    #"hpi": [sample_name.split("-")[2] for sample_name in counts.columns],
}, index=counts.columns)

design

res = deseq(meta=design, counts=counts, formula="~experiment", ref="mock", exp="S2")

res.to_csv('h1299_DEGs_24h.csv')
res

R[write to console]: converting counts to integer mode

R[write to console]: estimating size factors

R[write to console]: estimating dispersions

R[write to console]: gene-wise dispersion estimates

R[write to console]: mean-dispersion relationship

R[write to console]: final dispersion estimates

R[write to console]: fitting model and testing

experiment_S2_vs_mock

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
ENSG00000070669,5538.801686,-1.447477,0.123673,-11.704096,1.214472e-31,1.420811e-27
ENSG00000166592,431.547393,1.812637,0.187453,9.669802,4.051594e-22,2.369980e-18
ENSG00000159167,651.507890,1.435378,0.173402,8.277769,1.255039e-16,4.894235e-13
ENSG00000128965,474.957183,-1.527367,0.205016,-7.449984,9.335179e-14,2.730306e-10
ENSG00000161057,3560.609869,0.938351,0.127101,7.382721,1.550867e-13,3.628718e-10
...,...,...,...,...,...,...
ENSG00000119688,897.885487,-0.533730,0.193888,-2.752776,5.909230e-03,4.788471e-02
ENSG00000103274,429.828669,0.504467,0.183635,2.747125,6.012016e-03,4.854008e-02
ENSG00000049323,42.678282,1.234741,0.450248,2.742355,6.100035e-03,4.911515e-02
ENSG00000087266,359.686992,-0.530408,0.193556,-2.740333,6.137694e-03,4.935044e-02
ENSG00000213413,133.559222,-0.786591,0.287555,-2.735440,6.229703e-03,4.995291e-02

In [15]:
counts = counts36

design = pd.DataFrame({
    "experiment": [sample_name.split("-")[1] for sample_name in counts.columns],
    #"hpi": [sample_name.split("-")[2] for sample_name in counts.columns],
}, index=counts.columns)

design

res = deseq(meta=design, counts=counts, formula="~experiment", ref="mock", exp="S2")

res.to_csv('h1299_DEGs_36h.csv')
res

R[write to console]: converting counts to integer mode

R[write to console]: estimating size factors

R[write to console]: estimating dispersions

R[write to console]: gene-wise dispersion estimates

R[write to console]: mean-dispersion relationship

R[write to console]: final dispersion estimates

R[write to console]: fitting model and testing

experiment_S2_vs_mock

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
ENSG00000197061,8454.284303,0.635919,0.135315,4.699533,0.000003,0.040793

In [16]:
counts = counts36_1

design = pd.DataFrame({
    "experiment": [sample_name.split("-")[1] for sample_name in counts.columns],
    #"hpi": [sample_name.split("-")[2] for sample_name in counts.columns],
}, index=counts.columns)

design

res = deseq(meta=design, counts=counts, formula="~experiment", ref="mock", exp="S2")

res.to_csv('h1299_DEGs_36h_control4.csv')
res

R[write to console]: converting counts to integer mode

R[write to console]: estimating size factors

R[write to console]: estimating dispersions

R[write to console]: gene-wise dispersion estimates

R[write to console]: mean-dispersion relationship

R[write to console]: final dispersion estimates

R[write to console]: fitting model and testing

experiment_S2_vs_mock

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
ENSG00000023445,11639.129651,1.536164,0.119397,12.865994,6.993665e-38,8.182588e-34
ENSG00000166592,435.966436,2.140619,0.180997,11.826829,2.836558e-32,1.659386e-28
ENSG00000070669,5598.447178,-1.355771,0.117213,-11.566710,6.076879e-31,2.369983e-27
ENSG00000159167,664.774483,1.645530,0.153196,10.741331,6.509877e-27,1.904139e-23
ENSG00000056558,839.555048,1.525534,0.145613,10.476647,1.105958e-25,2.587942e-22
...,...,...,...,...,...,...
ENSG00000220161,119.781786,-0.791386,0.294074,-2.691109,7.121498e-03,4.878309e-02
ENSG00000106415,296.277246,-0.508360,0.188925,-2.690811,7.127848e-03,4.879802e-02
ENSG00000174151,271.196726,-0.550511,0.204809,-2.687931,7.189617e-03,4.913030e-02
ENSG00000130052,149.612174,-0.662020,0.246472,-2.685980,7.231750e-03,4.936492e-02
ENSG00000106025,91.087309,0.846550,0.315549,2.682786,7.301165e-03,4.963938e-02

# dif between mock at 4h and 36h

In [17]:
mock = pd.DataFrame()

mock[['H1299-mock-4h-A', 'H1299-mock-4h-B']] = counts4[['H1299-mock-4h-A', 'H1299-mock-4h-B']]
mock[['H1299-mock-36h-A', 'H1299-mock-36h-B']] = counts36[['H1299-mock-36h-A', 'H1299-mock-36h-B']]

In [18]:
counts = mock

design = pd.DataFrame({
    "experiment": [sample_name.split("-")[2] for sample_name in counts.columns],
    #"hpi": [sample_name.split("-")[2] for sample_name in counts.columns],
}, index=counts.columns)

design

                 experiment
H1299-mock-4h-A          4h
H1299-mock-4h-B          4h
H1299-mock-36h-A        36h
H1299-mock-36h-B        36h

In [19]:
res = deseq(meta=design, counts=counts, formula="~experiment", ref="4h", exp="36h")

res.to_csv('h1299_control_4_36.csv')
res

R[write to console]: converting counts to integer mode

R[write to console]: estimating size factors

R[write to console]: estimating dispersions

R[write to console]: gene-wise dispersion estimates

R[write to console]: mean-dispersion relationship

R[write to console]: final dispersion estimates

R[write to console]: fitting model and testing

experiment_36h_vs_4h

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
ENSG00000023445,10781.951802,1.399508,0.107959,12.963311,1.975341e-38,2.311149e-34
ENSG00000070669,5381.464020,-1.478656,0.120200,-12.301661,8.873064e-35,5.190743e-31
ENSG00000166592,401.190096,2.000270,0.179632,11.135352,8.441105e-29,3.292031e-25
ENSG00000159167,610.391389,1.551197,0.151161,10.261871,1.046588e-24,3.061270e-21
ENSG00000266402,2904.529717,-1.173848,0.132886,-8.833471,1.014766e-18,2.374552e-15
...,...,...,...,...,...,...
ENSG00000278615,155.243640,-0.736146,0.275493,-2.672104,7.537720e-03,4.824471e-02
ENSG00000149781,87.868727,-0.833421,0.312322,-2.668472,7.619719e-03,4.855704e-02
ENSG00000165475,68.542210,0.950882,0.356654,2.666120,7.673228e-03,4.884481e-02
ENSG00000167306,117.206096,0.728649,0.273496,2.664205,7.717062e-03,4.907045e-02
ENSG00000205583,89.293554,-0.819805,0.308502,-2.657374,7.875210e-03,4.972475e-02